"""empty message

Revision ID: 30043db07d25
Revises: 9767b5d6b8ba
Create Date: 2025-06-14 12:53:41.389271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30043db07d25'
down_revision = '9767b5d6b8ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('notes',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('notes',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
