"""empty message

Revision ID: 94d594b1a3bb
Revises: 30043db07d25
Create Date: 2025-06-17 12:26:18.157608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94d594b1a3bb'
down_revision = '30043db07d25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('booking_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_status', sa.VARCHAR(length=9), nullable=False))

    # ### end Alembic commands ###
