"""empty message

Revision ID: 9767b5d6b8ba
Revises: e65f47560e6a
Create Date: 2025-06-14 12:16:14.429609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9767b5d6b8ba'
down_revision = 'e65f47560e6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('client_name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('telephone', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('start_datetime', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('end_datetime', sa.DateTime(), nullable=False))
        batch_op.alter_column('client_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('artist_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('service_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('uq_artist_booking_slot', type_='unique')
        batch_op.drop_column('booking_time')
        batch_op.drop_column('booking_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_date', sa.DATE(), nullable=False))
        batch_op.add_column(sa.Column('booking_time', sa.TIME(), nullable=False))
        batch_op.create_unique_constraint('uq_artist_booking_slot', ['artist_id', 'booking_date', 'booking_time'])
        batch_op.alter_column('service_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('artist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('client_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('end_datetime')
        batch_op.drop_column('start_datetime')
        batch_op.drop_column('telephone')
        batch_op.drop_column('client_name')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
