"""Clean schema: removed user_id from clients and bookings

Revision ID: 9fe8f214402e
Revises: 15669934845d
Create Date: 2025-05-01 08:06:55.198607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fe8f214402e'
down_revision = '15669934845d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('booking_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('notes',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('booking_status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('pending', 'confirmed', 'cancelled', 'completed', name='bookingstatus'),
               nullable=False,
               existing_server_default=sa.text("'pending'"))
        batch_op.create_unique_constraint('uq_artist_booking_slot', ['artist_id', 'booking_date', 'booking_time'])

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.alter_column('client_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('client_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint('uq_artist_booking_slot', type_='unique')
        batch_op.alter_column('booking_status',
               existing_type=sa.Enum('pending', 'confirmed', 'cancelled', 'completed', name='bookingstatus'),
               type_=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'pending'"))
        batch_op.alter_column('notes',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('booking_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    # ### end Alembic commands ###
